import json
singles=["bảo lãnh bảo hành công trình|bao-lanh-bao-hanh-cong-trinh","bảo lãnh dự thầu|bao-lanh-du-thau","bảo lãnh ngân hàng là gì|bao-lanh-ngan-hang-la-gi","bảo lãnh tạm ứng là gì|bao-lanh-tam-ung-la-gi","cách nộp thuế điện tử|cach-nop-thue-dien-tu","cam kết tín dụng|cam-ket-tin-dung","công ty xuất nhập khẩu|cong-ty-xuat-nhap-khau","đăng ký thành lập doanh nghiệp online|dang-ky-thanh-lap-doanh-nghiep-online","điều kiện thành lập doanh nghiệp|dieu-kien-thanh-lap-doanh-nghiep","giấy phép kinh doanh|giay-phep-kinh-doanh","hồ sơ đăng ký thành lập doanh nghiệp|ho-so-dang-ky-thanh-lap-doanh-nghiep","hoàn thuế doanh nghiệp|hoan-thue-doanh-nghiep","hướng dẫn đăng ký thành lập doanh nghiệp|huong-dan-dang-ky-thanh-lap-doanh-nghiep","kê khai thuế doanh nghiệp|ke-khai-thue-doanh-nghiep","kiểm tra mã số thuế doanh nghiệp|kiem-tra-ma-so-thue-doanh-nghiep","quyết toán thuế doanh nghiệp|quyet-toan-thue-doanh-nghiep","rút tiền mặt từ tài khoản doanh nghiệp|rut-tien-mat-tu-tai-khoan-doanh-nghiep","vòng quay vốn|vong-quay-von"]
groups=["biến động tỷ giá với doanh nghiệp sme|bien-dong-ty-gia-voi-doanh-nghiep-sme","cách kiểm tra tài khoản ngân hàng của công ty|cach-kiem-tra-tai-khoan-ngan-hang-cua-cong-ty","cách quản lý tài chính kinh doanh|cach-quan-ly-tai-chinh-kinh-doanh","cách tính thuế thu nhập doanh nghiệp|cach-tinh-thue-thu-nhap-doanh-nghiep","công ty sử dụng tài khoản cá nhân|cong-ty-su-dung-tai-khoan-ca-nhan","điều kiện vay vốn ngân hàng|dieu-kien-vay-von-ngan-hang","doanh nghiệp mới thành lập được ưu đãi gì|doanh-nghiep-moi-thanh-lap-duoc-uu-dai-gi","lợi nhuận|loi-nhuan","nộp thuế đất qua ngân hàng|nop-thue-dat-qua-ngan-hang","phần mềm quản lý tài chính doanh nghiệp|phan-mem-quan-ly-tai-chinh-doanh-nghiep","quản lý tài chính doanh nghiệp là gì|quan-ly-tai-chinh-doanh-nghiep-la-gi","quản lý tài chính doanh nghiệp nhỏ|quan-ly-tai-chinh-doanh-nghiep-nho","tài khoản business là gì|tai-khoan-business-la-gi","thanh toán quốc tế|thanh-toan-quoc-te","thủ tục thành lập doanh nghiệp|thu-tuc-thanh-lap-doanh-nghiep","thủ tục vay vốn kinh doanh nhỏ|thu-tuc-vay-von-kinh-doanh-nho","thuế doanh nghiệp|thue-doanh-nghiep","thuế thu nhập doanh nghiệp|thue-thu-nhap-doanh-nghiep","thuế vat là gì|thue-vat-la-gi","tối ưu hóa chi phí trong doanh nghiệp|toi-uu-hoa-chi-phi-trong-doanh-nghiep","tra cứu nợ thuế doanh nghiệp|tra-cuu-no-thue-doanh-nghiep","xu hướng tỷ giá usd|xu-huong-ty-gia-usd"]
arts=[]; r=529
for s in singles:
    k,slug=s.split('|'); arts.append({'kw':k,'slug':slug,'row':r,'G':1,'platforms':[{'row':r,'p':'Webflow'}]}); r+=11
assert r==727
for s in groups:
    k,slug=s.split('|'); arts.append({'kw':k,'slug':slug,'row':r,'G':4,'platforms':[{'row':r+i,'p':p} for i,p in enumerate(['Mastodon','Pinterest','Wix','Webflow'])]}); r+=11
print(r-11)
for a in arts: a['url']='https://techcombank.com/thong-tin/blog/'+a['slug']
json.dump(arts,open('plan.json','w'),ensure_ascii=False,indent=1)
print(len(arts), sum(len(a['platforms']) for a in arts))
